### ISSUE TITLE
Feature Request: Allow other symbols for Lists

### ISSUE THREAD

**Issue by Overload119** [notaapp/issues#33]
Often when evaluating a decision or writing feedback I (and many people) use different tokens for lists.

```
- Negative
+ Positive
= Neutral
```

For example, 

```
Is Coffee good?
- Jitters
+ Energy Productivity
= Black
```

It would be great to treat these symbols the same within a list format. `-, +, =` and still get some of the indentation and such.

**Comment by erusev** [comment]
`-` and `+` are already supported, `=` is not, but `*` is. These three characters (`-`, `+`, and `*`) are the list markers according to the Markdown spec and we try to stay as close as possible to the spec.

Would `*` work for you instead of `=`?

Since I also use notes for writing about decisions, I'm also looking for a good way to mark points. The one that I find the most useful right now is using emoji at the start of a point, ex: `- 😃 positive`, `- 😡 negative`, etc. One benefit of this approach is that it lets you have a lot of point types (not just positive, negative, and natural).

**Comment by Overload119** [comment]
Ah I think that should help, that's good to know. 

Unfortunately these symbols are chosen and standardized at my company. So even if I solve the solution for myself, I'd still have to rejig it into their format which is why I opened the issue. 

Intuitively It seems the cost of supporting a single extra character is pretty small, but if you want to confirm to MD I can get behind that as well.
