### ISSUE TITLE
Pasting images broken

### ISSUE THREAD

**Issue by timster** [notaapp/issues#421]
When I paste an image into a note it gets inserted like this:

`![[1710425368.png]]`

When it should get inserted like this:

`![[.assets/1710425368.png]]`

It does get copied to the .assets directory but the link to the image in the note is not right.

**Comment by astoilkov** [comment]
That's actually the expected behavior. Wiki-links only contain the name of the file. The same happens with wiki-links for notes.

If you don't want wiki-links, you can switch to regular links through preferences:
![CleanShot 2024-03-14 at 17 04 34@2x](https://github.com/notaapp/talk/assets/884810/12999a07-f754-422c-b408-8a6cfba25836)

**Comment by timster** [comment]
OH that works. Thank you!
