### ISSUE TITLE
Support for elastic tabstops

### ISSUE THREAD

**Issue by diethardsteiner** [notaapp/issues#52]
For my technical documentation I use tables fairly regularly. It's quite some work to make a table look pleasant in text mode. Thankfully [elastic tabstops](https://nickgravgaard.com/elastic-tabstops/) exist that would make working with tables in text mode a lot easier. Could you please add support for it? A sample implementation of this feature can be found in MultiMarkdown Composer:
<img width="518" alt="image" src="https://user-images.githubusercontent.com/1726057/113605638-d88a1980-963e-11eb-8f9b-d516434a9e24.png">

**Comment by astoilkov** [comment]
@diethardsteiner We are actually considering having a way to more easily build tables instead of supporting elastic tabstops. You can imagine the table feature like an Excel table – you can create rows, columns, tab through cells. This will be easier to work with because you won't need to manually maintain the right amount of elastic tabstops in each cell.

I have written more on the topic in the [Tab characters](https://github.com/notaapp/issues/issues/11) issue.

**Comment by diethardsteiner** [comment]
Thanks for letting me know. Yes a table-like interface would be even better! (I guess it would be quite similar to what Typora is offering)
